#!/usr/bin/expect

set work_dir [lindex $argv 0] 
set release [lindex $argv 1] 
set password 3edc4rfv 
set timeout -1

#spawn bash -c "ssh shenrui@9.71.44.38 ls /build/lodestone730/latest|head -n1"
#spawn ssh shenrui@9.71.44.38 {ls -t /build/lodestone730|awk '/^[0-9]+[a-z]*$/{print $1}'|head -n1}
spawn $work_dir/getversion.sh $release
match_max 100000
expect "*?password:"
send -- "$password\r"
send -- "\r"
expect eof
